main: fr.lazik.economie.Main
name: E-conomie
description: Creation d un plugin d economie
author: MrLazik
version: 0.0.1
commands:
 monCompte:
  description: Mon argent !
 ePay:
  description: je te donne
  usage: /ePay [joueur] [montant]
 moreMoney:
  description: donne de l'argent
  usage: /moreMoney [somme] [joueur]
  permission: permission.moreMoney
 newPrime:
  description: creer une nouvelle prime
  usage: /newPrime [joueur] [somme]
 prime:
  discription: montre la prime en cours 
permission:
 plugin.moreMoney:
  description: etre op pour pouvoir faire cette commande
  default: op